name: Lint and Typecheck and Test
on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: requirements.txt
        allow-prereleases: true
    - run: pip install -r requirements.txt
    - run: ruff check monaco_dict_utils
    - run: ty check monaco_dict_utils --python "$pythonLocation"
    - run: black --check monaco_dict_utils
    - run: python -m pytest